name: Deploy to CWP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Static Project
        run: npm run build

      - name: Test SSH Connection (Debug)
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -p 22527 -i private_key -o StrictHostKeyChecking=no svnuniq@101.53.144.53 "echo ✅ SSH Connected Successfully"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Zero Downtime (Atomic Swap)
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Upload new build to a temp directory
          ssh -p 22527 -i private_key -o StrictHostKeyChecking=no svnuniq@101.53.144.53 "rm -rf /home/svnuniq/_deploy_tmp && mkdir /home/svnuniq/_deploy_tmp"
          scp -P 22527 -i private_key -o StrictHostKeyChecking=no -r ./out/* svnuniq@101.53.144.53:/home/svnuniq/_deploy_tmp/

          # Atomic swap: backup old, swap new, never down
          ssh -p 22527 -i private_key -o StrictHostKeyChecking=no svnuniq@101.53.144.53 "
            rm -rf /home/svnuniq/public_html_old &&
            mv /home/svnuniq/public_html /home/svnuniq/public_html_old &&
            mv /home/svnuniq/_deploy_tmp /home/svnuniq/public_html
          "

          rm -f private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
